In [1]:
import requests as rq
import pandas as pd
import numpy as np

In [2]:
link = "https://www.moneycontrol.com/company-facts/muthootfinance/dividends/MF10#MF10"

In [3]:

myobj = {'somekey': 'somevalue'}

rs= rq.post(link)

print(rs.status_code)

200

In [4]:
print(dir(rs))

['__attrs__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_content', '_content_consumed', '_next', 'apparent_encoding', 'close', 'connection', 'content', 'cookies', 'elapsed', 'encoding', 'headers', 'history', 'is_permanent_redirect', 'is_redirect', 'iter_content', 'iter_lines', 'json', 'links', 'next', 'ok', 'raise_for_status', 'raw', 'reason', 'request', 'status_code', 'text', 'url']

In [5]:
import bs4 as bs
from bs4 import BeautifulSoup

data = []
soup = BeautifulSoup(rs.text, 'html.parser')
table = soup.find('table', attrs={'class':'mctable1'})
table_body = table.find('tbody')

rows = table_body.find_all('tr')
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) # Get rid of empty values

In [6]:
type(data)

list

In [7]:
df = pd.DataFrame(data)

In [8]:
df.head(20)

,0,1,2,3,4,5
0,04-04-2022,25-04-2022,Interim,200,20.00,Rs.20.0000 per share(200%)Interim Dividend
1,08-04-2021,22-04-2021,Interim,200,20.00,Rs.20.0000 per share(200%)Interim Dividend
2,09-03-2020,23-03-2020,Interim,150,15.00,Rs.15.0000 per share(150%)Interim Dividend
3,02-04-2019,11-04-2019,Interim,120,12.00,Rs.12.0000 per share(120%)Interim Dividend
4,31-01-2018,15-02-2018,Interim,100,10.00,Rs.10.0000 per share(100%)Interim Dividend
5,17-03-2017,30-03-2017,Interim,60,6.00,Rs.6.0000 per share(60%)Interim Dividend
6,08-03-2016,16-03-2016,Interim,20,2.00,Rs.2.0000 per share(20%)Second Interim Dividend
7,27-10-2015,05-11-2015,Interim,40,4.00,Rs.4.0000 per share(40%)Interim Dividend
8,05-05-2015,22-09-2015,Final,20,2.00,Rs.2.0000 per share(20%)Dividend
9,26-09-2014,22-10-2014,Interim,40,4.00,Rs.4.0000 per share (40%) First Interim Dividend
10,26-05-2014,10-09-2014,Final,10,1.00,Rs.1.0000 per share(10%)Dividend
11,23-01-2014,04-02-2014,Interim,20,2.00,Rs.2.0000 per share(20%)Interim Dividend
12,22-10-2013,05-11-2013,Interim,30,3.00,Rs.3.0000 per share(30%)First Interim Dividend
13,14-05-2013,12-09-2013,Final,45,4.50,Rs.4.5000 per share(45%)Dividend
14,15-05-2012,16-08-2012,Final,40,4.00,Rs.4.00 per share(40%)Dividend

# New approach

In [9]:
import pandas as pd
import numpy as np

all_tables = pd.read_html(link)
print(f'Total tables: {len(all_tables)}')

Total tables: 1

In [10]:
df = all_tables[0]
df.head(20)

,Announcement Date,Ex-Date,Dividend Type,Dividend (%),Dividend (Rs),Remarks
0,04-04-2022,25-04-2022,Interim,200,20.0,Rs.20.0000 per share(200%)Interim Dividend
1,08-04-2021,22-04-2021,Interim,200,20.0,Rs.20.0000 per share(200%)Interim Dividend
2,09-03-2020,23-03-2020,Interim,150,15.0,Rs.15.0000 per share(150%)Interim Dividend
3,02-04-2019,11-04-2019,Interim,120,12.0,Rs.12.0000 per share(120%)Interim Dividend
4,31-01-2018,15-02-2018,Interim,100,10.0,Rs.10.0000 per share(100%)Interim Dividend
5,17-03-2017,30-03-2017,Interim,60,6.0,Rs.6.0000 per share(60%)Interim Dividend
6,08-03-2016,16-03-2016,Interim,20,2.0,Rs.2.0000 per share(20%)Second Interim Dividend
7,27-10-2015,05-11-2015,Interim,40,4.0,Rs.4.0000 per share(40%)Interim Dividend
8,05-05-2015,22-09-2015,Final,20,2.0,Rs.2.0000 per share(20%)Dividend
9,26-09-2014,22-10-2014,Interim,40,4.0,Rs.4.0000 per share (40%) First Interim Dividend
10,26-05-2014,10-09-2014,Final,10,1.0,Rs.1.0000 per share(10%)Dividend
11,23-01-2014,04-02-2014,Interim,20,2.0,Rs.2.0000 per share(20%)Interim Dividend
12,22-10-2013,05-11-2013,Interim,30,3.0,Rs.3.0000 per share(30%)First Interim Dividend
13,14-05-2013,12-09-2013,Final,45,4.5,Rs.4.5000 per share(45%)Dividend
14,15-05-2012,16-08-2012,Final,40,4.0,Rs.4.00 per share(40%)Dividend

In [11]:
# adding column with constant value
df['Stock'] = 'MUTHOOTFIN'
df.head(20)

,Announcement Date,Ex-Date,Dividend Type,Dividend (%),Dividend (Rs),Remarks,Stock
0,04-04-2022,25-04-2022,Interim,200,20.0,Rs.20.0000 per share(200%)Interim Dividend,MUTHOOTFIN
1,08-04-2021,22-04-2021,Interim,200,20.0,Rs.20.0000 per share(200%)Interim Dividend,MUTHOOTFIN
2,09-03-2020,23-03-2020,Interim,150,15.0,Rs.15.0000 per share(150%)Interim Dividend,MUTHOOTFIN
3,02-04-2019,11-04-2019,Interim,120,12.0,Rs.12.0000 per share(120%)Interim Dividend,MUTHOOTFIN
4,31-01-2018,15-02-2018,Interim,100,10.0,Rs.10.0000 per share(100%)Interim Dividend,MUTHOOTFIN
5,17-03-2017,30-03-2017,Interim,60,6.0,Rs.6.0000 per share(60%)Interim Dividend,MUTHOOTFIN
6,08-03-2016,16-03-2016,Interim,20,2.0,Rs.2.0000 per share(20%)Second Interim Dividend,MUTHOOTFIN
7,27-10-2015,05-11-2015,Interim,40,4.0,Rs.4.0000 per share(40%)Interim Dividend,MUTHOOTFIN
8,05-05-2015,22-09-2015,Final,20,2.0,Rs.2.0000 per share(20%)Dividend,MUTHOOTFIN
9,26-09-2014,22-10-2014,Interim,40,4.0,Rs.4.0000 per share (40%) First Interim Dividend,MUTHOOTFIN
10,26-05-2014,10-09-2014,Final,10,1.0,Rs.1.0000 per share(10%)Dividend,MUTHOOTFIN
11,23-01-2014,04-02-2014,Interim,20,2.0,Rs.2.0000 per share(20%)Interim Dividend,MUTHOOTFIN
12,22-10-2013,05-11-2013,Interim,30,3.0,Rs.3.0000 per share(30%)First Interim Dividend,MUTHOOTFIN
13,14-05-2013,12-09-2013,Final,45,4.5,Rs.4.5000 per share(45%)Dividend,MUTHOOTFIN
14,15-05-2012,16-08-2012,Final,40,4.0,Rs.4.00 per share(40%)Dividend,MUTHOOTFIN

In [12]:
df_links = pd.read_csv('../../configs/moneycontrol-dividend-links.csv')
df_links.head()

        STOCK                                                URL
0    AARTIIND  https://www.moneycontrol.com/company-facts/aar...
1  ALKYLAMINE  https://www.moneycontrol.com/company-facts/alk...
2  APOLLOHOSP  https://www.moneycontrol.com/company-facts/apo...
3    ASHOKLEY  https://www.moneycontrol.com/company-facts/ash...
4  ASIANPAINT  https://www.moneycontrol.com/company-facts/asi...

In [13]:
import time


path = './div/'
for index, row in df_links.iterrows():
    #print(row['STOCK'], row['URL'])
    stock_name = row['STOCK']
    url = row['URL']
    all_tables = pd.read_html(url)
    #print(f'Total tables: {len(all_tables)}')
    df_temp = all_tables[0]
    df_temp['Stockname'] = stock_name
    
    df_temp['Announcement Date'] = pd.to_datetime(df_temp['Announcement Date'])
    df_temp['Ex-Date']           = pd.to_datetime(df_temp['Ex-Date'])
    
    df_temp['Announce Date']     = df_temp['Announcement Date'].dt.strftime('%m/%d/%Y')
    df_temp['Ex Date']           = df_temp['Ex-Date'].dt.strftime('%m/%d/%Y')
    
    df_temp.to_csv(str(path+stock_name+'.csv'), index=False)
    time.sleep(1)
    print("Done: "+stock_name)

Done: AARTIIND
Done: ALKYLAMINE
Done: APOLLOHOSP
Done: ASHOKLEY
Done: ASIANPAINT
Done: ASTRAL
Done: BAJAJ-AUTO
Done: BAJAJELEC
Done: BAJAJFINSV
Done: BAJFINANCE
Done: BALAMINES
Done: BALKRISIND
Done: BERGEPAINT
Done: BHARTIARTL
Done: BRITANNIA
Done: CAMS
Done: CDSL
Done: DABUR
Done: DEEPAKNTR
Done: DIVISLAB
Done: DIXON
Done: DMART
Done: DRREDDY
Done: EICHERMOT
Done: HAVELLS
Done: HCLTECH
Done: HDFC
Done: HDFCAMC
Done: HDFCBANK
Done: HDFCLIFE
Done: HEROMOTOCO
Done: HINDUNILVR
Done: HNDFDS
Done: ICICIBANK
Done: ICICIGI
Done: ICICIPRULI
Done: INFY
Done: ISEC
Done: ITC
Done: JUBLFOOD
Done: KOTAKBANK
Done: LATENTVIEW
Done: LTI
Done: LTTS
Done: LXCHEM
Done: M&M
Done: MARICO
Done: MARUTI
Done: METROPOLIS
Done: MINDAIND
Done: MOLDTKPAC
Done: MOSCHIP
Done: MOTHERSUMI
Done: MTARTECH
Done: MUTHOOTFIN
Done: NAUKRI
Done: NAVINFLUOR
Done: NESTLEIND
Done: PARAS
Done: PGHH
Done: PIDILITIND
Done: PIIND
Done: POLYCAB
Done: PRINCEPIPE
Done: RELAXO
Done: RELIANCE
Done: ROSSARI
Done: SBICARD
Done: SBIN
Done: SUPREMEIND
Done: TATACHEM
Done: TATACONSUM
Done: TATAELXSI
Done: TATAMOTORS
Done: TATAPOWER
Done: TATASTEEL
Done: TCS
Done: TECHM
Done: TITAN
Done: TRENT
Done: TRIDENT
Done: VOLTAS
Done: WIPRO